name: CI Workflow

# Déclencheurs du workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Clean Maven cache
        run: mvn clean -f BackendStage/pom.xml

      - name: Build with Maven
        run: mvn -e -X package -f BackendStage/pom.xml

      - name: Run tests
        run: mvn test -f BackendStage/pom.xml
      
      - name: Run SonarQube analysis
        run: mvn sonar:sonar \
          -Dsonar.projectKey=manageroci \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} \
          -f BackendStage/pom.xml
    
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: BackendStage/target/
