name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List resource files
        run: |
          echo "Listing resource files:"
          find BackendStage/src/main/resources -type f -exec file {} \;

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Clean Maven cache
        run: mvn clean --file BackendStage/pom.xml

      - name: Build with Maven
        run: mvn -e -X package --file BackendStage/pom.xml

      - name: Run tests
        run: mvn test --file BackendStage/pom.xml
      
      - name: Run SonarQube analysis
        run: mvn sonar:sonar \
          -Dsonar.projectKey=manageroci \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
        working-directory: BackendStage
    
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: BackendStage/target/
