name: CI Workflow

on:
  push:
    branches: 
      - '*'
      
  workflow_dispatch:  # Ajout du déclencheur pour les exécutions manuelles

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: BackendStage
      run: mvn clean install --file pom.xml

    - name: Run SonarCloud analysis
      uses: sonarsource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    - name: Upload SonarCloud report
      uses: actions/upload-artifact@v3
      with:
        name: sonarcloud-report
        path: ./path-to-report

    # - name: SonarCloud Scan
    #   working-directory: BackendStage
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   run: |
    #     mvn sonar:sonar \
    #         -Dsonar.branch.name=${{ github.ref_name }} \
    #         -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sonarcloud-artifact
        path: BackendStage/target/
