name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Clean Maven cache
        run: mvn clean --file BackendStage/pom.xml

      - name: Build and Test with Maven
        run: mvn -e -X clean install --file BackendStage/pom.xml

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: mvn sonar:sonar \
          -Dsonar.projectKey=manageroci \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
    
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: BackendStage/target/
