name: CI Workflow

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: BackendStage
      run: mvn clean install --file pom.xml

    - name: SonarCloud Scan
      working-directory: BackendStage
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for PR information
      run: |
        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=manageroci \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} \
          -Dsonar.organization=manageroci \
          -Dsonar.branch.name=${GITHUB_REF##*/}
          
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2



    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: BackendStage/target/
