name: CI Workflow

# Déclencheurs du workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List resource files
        run: |
          echo "Listing resource files:"
          find BackendStage/src/main/resources -type f -exec file {} \;

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Clean Maven cache
        run: mvn clean --file BackendStage/pom.xml

      - name: Build with Maven
        run: mvn -e -X package --file BackendStage/pom.xml

      - name: Run tests
        run: mvn test --file BackendStage/pom.xml

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: BackendStage/target/

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Run SonarQube Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar --file BackendStage/pom.xml
