name: CI Workflow

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: BackendStage
      run: mvn clean install --file pom.xml
    
    - name: SonarCloud Scan
      working-directory: BackendStage
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # - name: SonarCloud Scan
    #   working-directory: BackendStage
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   run: |
    #     mvn sonar:sonar \
    #         -Dsonar.projectKey=manageroci2 \
    #         -Dsonar.host.url=https://sonarcloud.io \
    #         -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
    #         -Dsonar.organization=manageroci \

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: BackendStage/target/
